# Generated by Django 4.2.6 on 2023-10-21 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_user_id', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('priority', models.CharField(default='1', max_length=20)),
                ('status', models.CharField(default='0', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AgentResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_user_id', models.CharField(max_length=20)),
                ('response_body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('priority', models.CharField(max_length=20)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='webapp.clientmessages')),
            ],
        ),
    ]
