# Generated by Django 4.2.6 on 2023-10-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_clientmessages_agentresponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessages',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientmessages',
            name='priority',
            field=models.CharField(default='2', max_length=20),
        ),
    ]
