# Generated by Django 4.2.6 on 2023-10-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_clientmessages_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessages',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clientmessages',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientmessages',
            name='status',
            field=models.CharField(default='unread', max_length=500),
        ),
    ]
