# Generated by Django 4.2.6 on 2023-10-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_agentresponses_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentresponses',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.clientmessages'),
        ),
    ]
